[package]
name = "rshttp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
mime_guess = "2.0.5"
notify = "7.0.0"
tokio = { version = "1.42.0", features = ["full"] }
